Repository idaholab/raven, pull requests merged in 2018-11, with the labels that each got.

#824 fix failed test caused by PR#777
  doc/workshop/forwardSampling/Inputs/previous/ForwardSampling6.xml
  doc/workshop/forwardSampling/Inputs/previous/gold/r6/Stat_basicStatPP_dump.csv
  tests/framework/ROM/SKLearn/occ.xml
Labels: Ready To Review, comments addressed, defect, devel, priority_critical

#821 PRA plugin fixes
  plugins/PRAplugin/src/MarkovModel.py
  plugins/PRAplugin/tests/gold/ensembleDiscrete/Print_sim_PS.csv
  plugins/PRAplugin/tests/gold/ensembleMixed/Print_sim_PS.csv
  plugins/PRAplugin/tests/test_ensemblePRAModel_discrete.xml
Labels: defect, priority_normal

#748 SAPHIRE Code Interface
  doc/user_manual/couplingAcode.tex
  doc/user_manual/existing_interfaces.tex
  doc/user_manual/model.tex
  framework/CodeInterfaceBaseClass.py
  framework/CodeInterfaces/CobraTF/CTFinterface.py
  framework/CodeInterfaces/Dymola/DymolaInterface.py
  framework/CodeInterfaces/Generic/GenericCodeInterface.py
  framework/CodeInterfaces/MAMMOTH/MAMMOTHInterface.py
  framework/CodeInterfaces/MELCOR/melcorCombinedInterface.py
  framework/CodeInterfaces/MELCOR/melcorInterface.py
  framework/CodeInterfaces/MELCOR/melgenInterface.py
  framework/CodeInterfaces/MooseBasedApp/BisonAndMeshInterface.py
  framework/CodeInterfaces/MooseBasedApp/BisonMeshScriptInterface.py
  framework/CodeInterfaces/MooseBasedApp/CubitInterface.py
  framework/CodeInterfaces/MooseBasedApp/MooseBasedAppInterface.py
  framework/CodeInterfaces/OpenModelica/OpenModelicaInterface.py
  framework/CodeInterfaces/PHISICS/PhisicsInterface.py
  framework/CodeInterfaces/PHISICS/PhisicsRelapInterface.py
  framework/CodeInterfaces/RAVEN/RAVENInterface.py
  framework/CodeInterfaces/RELAP5/Relap5Interface.py
  framework/CodeInterfaces/RELAP7/RELAP7Interface.py
  framework/CodeInterfaces/Rattlesnake/RattlesnakeInterface.py
  framework/CodeInterfaces/SCALE/ScaleInterface.py
  framework/CodeInterfaces/Saphire/SaphireData.py
  framework/CodeInterfaces/Saphire/SaphireInterface.py
  framework/CodeInterfaces/WorkshopExamples/BatemanInterface.py
  framework/CodeInterfaces/WorkshopExamples/ProjectileInterface.py
  framework/Models/Code.py
  tests/framework/CodeInterfaceTests/SaphireInterface/gold/testSaphire/saphirePrint.csv
  tests/framework/CodeInterfaceTests/SaphireInterface/testSaphire/Class_Chg_DEMO.mac
  tests/framework/CodeInterfaceTests/SaphireInterface/testSaphire/demo.zip
  tests/framework/CodeInterfaceTests/SaphireInterface/testSaphire/sample/1/Publish/et_uq.csv
  tests/framework/CodeInterfaceTests/SaphireInterface/testSaphire/sample/1/Publish/ft_uq.csv
  tests/framework/CodeInterfaceTests/SaphireInterface/testSaphire/sample/2/Publish/et_uq.csv
  tests/framework/CodeInterfaceTests/SaphireInterface/testSaphire/sample/2/Publish/ft_uq.csv
  tests/framework/CodeInterfaceTests/SaphireInterface/test_saphire.xml
  tests/framework/CodeInterfaceTests/SaphireInterface/tests
  tests/framework/CodeInterfaceTests/test_generic_IO.xml
  tests/framework/CodeInterfaceTests/test_generic_interface.xml
  tests/framework/CodeInterfaceTests/test_generic_interface_custom_out_file.xml
  tests/framework/CodeInterfaceTests/tests
  tests/framework/hybridModel/test_code.xml
Labels: Ready To Review

#789 Update Cross Validations
  doc/user_manual/model.tex
  doc/user_manual/postprocessor.tex
  doc/workshop/ensembleModels/inputs/hybridExample/test_hybrid_model.xml
  framework/CrossValidations/SklCrossValidation.py
  framework/PostProcessors/CrossValidation.py
  framework/utils/InputData.py
  scripts/conversionScripts/updateCrossValidation.py
  tests/cluster_tests/InternalParallel/test_hybrid_model_code.xml
  tests/cluster_tests/InternalParallel/test_hybrid_model_external.xml
  tests/framework/PostProcessors/CrossValidations/test_LabelKFold.xml
  tests/framework/PostProcessors/CrossValidations/test_cross_validation.xml
  tests/framework/PostProcessors/CrossValidations/test_labelShuffleSplit.xml
  tests/framework/PostProcessors/CrossValidations/test_leaveOneLabelOut.xml
  tests/framework/PostProcessors/CrossValidations/test_leavePLabelOut.xml
  tests/framework/PostProcessors/CrossValidations/test_shuffleSplit.xml
  tests/framework/PostProcessors/CrossValidations/test_stratifiedKFold.xml
  tests/framework/PostProcessors/CrossValidations/test_stratifiedShuffleSplit.xml
  tests/framework/hybridModel/test_code.xml
  tests/framework/hybridModel/test_hybrid_model.xml
  tests/framework/hybridModel/test_rom_rom.xml
  tests/framework/hybridModel/test_train_rom.xml
Labels: Ready To Review

#830 Index method for SampleSelector
  doc/user_manual/postprocessor.tex
  framework/PostProcessors/SampleSelector.py
  tests/framework/PostProcessors/SampleSelector/basic.xml
  tests/framework/PostProcessors/SampleSelector/gold/Basic/selected_printed_index.csv
  tests/framework/PostProcessors/SampleSelector/gold/Basic/selected_printed_max.csv
  tests/framework/PostProcessors/SampleSelector/tests
Labels: Ready To Review, comments addressed

#844 Alfoa/generic codeinterface fix
  framework/CodeInterfaces/Generic/GenericCodeInterface.py
  framework/Models/Code.py
  framework/Models/Model.py
  framework/Models/PostProcessor.py
  tests/framework/CodeInterfaceTests/GenericInterface/inp.three
  tests/framework/CodeInterfaceTests/test_generic_interface.xml
Labels: comments addressed, defect, priority_critical
