Repository idaholab/raven, pull requests merged in 2019-10, with the labels that each got.

#1045 Conjugate gradient optimizer
  developer_tools/XSDSchemas/Optimizers.xsd
  doc/tests/optimization_functions.tex
  doc/user_manual/optimizer.tex
  framework/Models/Model.py
  framework/Optimizers/Conjugate.py
  framework/Optimizers/Factory.py
  framework/Optimizers/FiniteDifference.py
  framework/Optimizers/GradientBasedOptimizer.py
  framework/Optimizers/Optimizer.py
  framework/Optimizers/SPSA.py
  rook/XMLDiff.py
  tests/framework/AnalyticModels/optimizing/diagonal_valley.py
  tests/framework/AnalyticModels/optimizing/plotWalk3d.py
  tests/framework/AnalyticModels/optimizing/plot_valley3d.py
  tests/framework/Optimizers/Valley/dvalley_plotdata.pk
  tests/framework/Optimizers/conjugate.xml
  tests/framework/Optimizers/gold/Conjugate/opt_export_1.csv
  tests/framework/Optimizers/gold/StochasticFiniteDifference/opt_export.csv
  tests/framework/Optimizers/tests
  tests/framework/ROM/TimeSeries/ARMA/tests
Labels: task

#1062 Adding paramInput to local input and checks inside optimizer
  doc/tests/optimization_functions.tex
  doc/user_manual/optimizer.tex
  doc/user_manual/raven_user_manual.tex
  framework/Optimizers/FiniteDifference.py
  framework/Optimizers/GradientBasedOptimizer.py
  framework/Optimizers/Optimizer.py
  framework/Optimizers/SPSA.py
  tests/framework/AnalyticModels/optimizing/paraboloid.py
  tests/framework/Optimizers/gold/OptIteration/opt_export_1.csv
  tests/framework/Optimizers/gold/StochasticFiniteDifference/opt_export.csv
  tests/framework/Optimizers/optIteration.xml
  tests/framework/Optimizers/tests
Labels: requirements

#1021 Neutrino Interface
  doc/user_manual/existing_interfaces.tex
  framework/CodeInterfaces/Neutrino/neutrinoInterface.py
  tests/framework/CodeInterfaceTests/Neutrino/Neutrino_Base/NeutrinoInput.nescene
  tests/framework/CodeInterfaceTests/Neutrino/Neutrino_Base/sampleNeutrino/1/NeutrinoInput.nescene
  tests/framework/CodeInterfaceTests/Neutrino/Neutrino_Base/sampleNeutrino/1/NeutrinoInput/Measurements/results.csv
  tests/framework/CodeInterfaceTests/Neutrino/Neutrino_Base/sampleNeutrino/2/NeutrinoInput.nescene
  tests/framework/CodeInterfaceTests/Neutrino/Neutrino_Base/sampleNeutrino/2/NeutrinoInput/Measurements/results.csv
  tests/framework/CodeInterfaceTests/Neutrino/Neutrino_Base/sampleNeutrino/3/NeutrinoInput.nescene
  tests/framework/CodeInterfaceTests/Neutrino/Neutrino_Base/sampleNeutrino/3/NeutrinoInput/Measurements/results.csv
  tests/framework/CodeInterfaceTests/Neutrino/Neutrino_Base/sampleNeutrino/NeutrinoInput.nescene
  tests/framework/CodeInterfaceTests/Neutrino/gold/Neutrino_Base/NeutrinoInput.nescene
  tests/framework/CodeInterfaceTests/Neutrino/gold/Neutrino_Base/out_dump.csv
  tests/framework/CodeInterfaceTests/Neutrino/test_neutrino_base.xml
  tests/framework/CodeInterfaceTests/Neutrino/tests
  tests/framework/DataObjects/DataobjectsAttributes/DatabaseStorage/testGridRavenDatabase.h5
Labels: FutureRAVENv2.0, external interfaces, task
