Repository idaholab/raven, pull requests merged in 2020-04, with the labels that each got.

#1197 Interfaced PPs manual fixes
  doc/user_manual/postprocessor.tex
Labels: FutureRAVENv2.0, defect, priority_critical

#1201 ARMA workshop
  doc/workshop/ARMA/ARMA.pptx
  doc/workshop/ARMA/inputs/1_arma.xml
  doc/workshop/ARMA/inputs/2_arma_Fourier.xml
  doc/workshop/ARMA/inputs/3_arma_pk.xml
  doc/workshop/ARMA/inputs/4_arma_unpk.xml
  doc/workshop/ARMA/inputs/5_arma_Ensemblemodel.xml
  doc/workshop/ARMA/inputs/Solutions/r1_arma.xml
  doc/workshop/ARMA/inputs/Solutions/r2_arma_Fourier.xml
  doc/workshop/ARMA/inputs/Solutions/r3_arma_pk.xml
  doc/workshop/ARMA/inputs/Solutions/r4_arma_unpk.xml
  doc/workshop/ARMA/inputs/Solutions/r5_arma_Ensemblemodel.xml
  doc/workshop/ARMA/inputs/r1/dataSet.csv
  doc/workshop/ARMA/inputs/r1/dataSet_0.csv
  doc/workshop/ARMA/inputs/r2/dataSet.csv
  doc/workshop/ARMA/inputs/r2/dataSet_0.csv
  doc/workshop/ARMA/inputs/r3/dataSet.csv
  doc/workshop/ARMA/inputs/r3/dataSet_0.csv
  doc/workshop/ARMA/inputs/r5/after_arma.py
Labels: FutureRAVENv2.0

#1198 Continuous Simulated Annealing
  developer_tools/XSDSchemas/Optimizers.xsd
  doc/user_manual/Makefile
  doc/user_manual/generated/generateOptimizerDoc.py
  doc/user_manual/generated/optimizer.tex
  doc/user_manual/raven_user_manual.tex
  framework/Models/Model.py
  framework/Optimizers/Factory.py
  framework/Optimizers/GradientDescent.py
  framework/Optimizers/Optimizer.py
  framework/Optimizers/RavenSampled.py
  framework/Optimizers/SimulatedAnnealing.py
  framework/Optimizers/__init__.py
  framework/utils/mathUtils.py
  tests/framework/AnalyticModels/optimizing/eggHolder.py
  tests/framework/Optimizers/SimulatedAnnealing/BoltzmanEggHolder/test_simulatedAnnealing_eggHold.xml
  tests/framework/Optimizers/SimulatedAnnealing/BoltzmanSA/test_simulatedAnnealing.xml
  tests/framework/Optimizers/SimulatedAnnealing/CauchyEggHolder/test_simulatedAnnealing_eggHold.xml
  tests/framework/Optimizers/SimulatedAnnealing/CauchySA/test_simulatedAnnealing.xml
  tests/framework/Optimizers/SimulatedAnnealing/ExponentialEggHolder/test_simulatedAnnealing_eggHold.xml
  tests/framework/Optimizers/SimulatedAnnealing/ExponentialSA/test_simulatedAnnealing.xml
  tests/framework/Optimizers/SimulatedAnnealing/FunctionallyConstrainedSA/test_funcConstrSimulatedAnnealing.xml
  tests/framework/Optimizers/SimulatedAnnealing/VeryFastSA/test_simulatedAnnealing.xml
  tests/framework/Optimizers/SimulatedAnnealing/gold/BoltzmanEggHolder/opt_export_0.csv
  tests/framework/Optimizers/SimulatedAnnealing/gold/BoltzmanSA/opt_export_0.csv
  tests/framework/Optimizers/SimulatedAnnealing/gold/CauchyEggHolder/opt_export_0.csv
  tests/framework/Optimizers/SimulatedAnnealing/gold/CauchySA/opt_export_0.csv
  tests/framework/Optimizers/SimulatedAnnealing/gold/ExponentialEggHolder/opt_export_0.csv
  tests/framework/Optimizers/SimulatedAnnealing/gold/ExponentialSA/opt_export_0.csv
  tests/framework/Optimizers/SimulatedAnnealing/gold/FunctionallyConstrainedSA/opt_export_0.csv
  tests/framework/Optimizers/SimulatedAnnealing/gold/VeryFastSA/opt_export_0.csv
  tests/framework/Optimizers/SimulatedAnnealing/tests
  tests/framework/PostProcessors/BasicStatistics/print_xml.xml
Labels: FutureRAVENv2.0

#1209 Cogljj/fix 1089
  tests/framework/PostProcessors/BasicStatistics/gold/HeavyXmlWrite/stats_basicStatPP_dump.xml
  tests/framework/PostProcessors/BasicStatistics/gold/HeavyXmlWrite/stats_basicStatPP_dump_0.csv
  tests/framework/user_guide/AdaptiveSamplingStrategies/gold/LSsearch/1-historyPlot_line-line-line-line.png
  tests/framework/user_guide/AdaptiveSamplingStrategies/gold/LSsearch/1-limitSurfacePlot_scatter.png
  tests/framework/user_guide/AdaptiveSamplingStrategies/gold/LSsearch/1-samplesPlot3D_scatter-scatter.png
  tests/framework/user_guide/DataMining/gold/dataMiningAnalysis/1-PlotKMeans1_dataMining-dataMining.png
  tests/framework/user_guide/DataMining/gold/dataMiningAnalysis/1-PlotLabels_dataMining.png
  tests/framework/user_guide/DataMining/gold/dataMiningAnalysis/1-PlotPCA1_dataMining.png
  tests/framework/user_guide/DataMining/gold/dataMiningAnalysis/samplesDump.csv
  tests/framework/user_guide/StatisticalAnalysis/gold/StatisticalAnalysis/statisticalAnalysis_basicStatPP_dump.csv
Labels: FutureRAVENv2.0, Ready To Review

#1196 Mandd/pareto frontier pp
  doc/user_manual/postprocessor.tex
  framework/PostProcessors/ParetoFrontierPostProcessor.py
  framework/PostProcessors/__init__.py
  tests/framework/PostProcessors/ParetoFrontierPostProcessor/ParetoFrontier/data.csv
  tests/framework/PostProcessors/ParetoFrontierPostProcessor/gold/ParetoFrontier/PrintPareto.csv
  tests/framework/PostProcessors/ParetoFrontierPostProcessor/test_paretoFrontier.xml
  tests/framework/PostProcessors/ParetoFrontierPostProcessor/tests
Labels: FutureRAVENv2.0, priority_minor
