Repository idaholab/raven, pull requests merged in 2021-12, with the labels that each got.

#1619 Adding DSS capabilities
  doc/theory_manual/Makefile
  doc/theory_manual/dssPostProcessor.tex
  doc/theory_manual/raven_theory_manual.bib
  doc/theory_manual/raven_theory_manual.tex
  doc/user_manual/metrics.tex
  doc/user_manual/postprocessor.tex
  doc/user_manual/raven_user_manual.tex
  framework/MetricDistributor.py
  framework/Metrics/metrics/DSS.py
  framework/Metrics/metrics/Factory.py
  framework/Models/PostProcessors/Factory.py
  framework/Models/PostProcessors/Validations/PPDSS.py
  framework/Models/PostProcessors/Validations/__init__.py
  tests/framework/PostProcessors/Validation/DSS/lorentzAttractor_timeScale_I.py
  tests/framework/PostProcessors/Validation/DSS/lorentzAttractor_timeScale_II.py
  tests/framework/PostProcessors/Validation/gold/DSS/pp2_print_0.csv
  tests/framework/PostProcessors/Validation/gold/DSS/pp2_print_1.csv
  tests/framework/PostProcessors/Validation/gold/DSS/pp2_print_2.csv
  tests/framework/PostProcessors/Validation/gold/DSS/pp2_print_3.csv
  tests/framework/PostProcessors/Validation/test_validation_dss.xml
  tests/framework/PostProcessors/Validation/tests
Labels: RAVENv3.0

#1723 minor changes to twoPointsCrossovers
  framework/Optimizers/crossOverOperators/crossovers.py
  framework/Optimizers/parentSelectors/parentSelectors.py
  framework/Optimizers/survivorSelectors/survivorSelectors.py
  tests/framework/Optimizers/GeneticAlgorithms/discrete/unconstrained/testGAMaxwoRepTwoPointsCrossover.xml
  tests/framework/Optimizers/GeneticAlgorithms/gold/discrete/unconstrained/MaxwoReplacementTwoPointsCrossover/opt_export_0.csv
  tests/framework/Optimizers/GeneticAlgorithms/gold/discrete/unconstrained/simpleKnapsackTournament/PrintOptOut_1.csv
  tests/framework/Optimizers/GeneticAlgorithms/tests
  tests/framework/unit_tests/Optimizers/test1pointCrossover.py
  tests/framework/unit_tests/Optimizers/test2pointsCrossover.py
  tests/framework/unit_tests/Optimizers/test2pointsCrossoverSmallArray.py
  tests/framework/unit_tests/Optimizers/testAgeBased.py
  tests/framework/unit_tests/Optimizers/testFitnessBased.py
  tests/framework/unit_tests/Optimizers/testRankSelection.py
  tests/framework/unit_tests/Optimizers/testTournamentSelection.py
  tests/framework/unit_tests/Optimizers/tests
Labels: defect, RAVENv3.0

#1738 Removing directly calling setup.py
  build_raven
  crow/setup.py
Labels: priority_normal
