Repository idaholab/raven, pull requests merged in 2021-06, with the labels that each got.

#1578 GA deepCopy cleaning
  framework/Optimizers/GeneticAlgorithm.py
  framework/Optimizers/crossOverOperators/crossovers.py
  framework/Optimizers/mutators/mutators.py
  framework/Optimizers/parentSelectors/parentSelectors.py
  framework/Optimizers/repairOperators/repair.py
  framework/Optimizers/survivorSelectors/survivorSelectors.py
Labels: priority_normal, task

#1590 Multi-threading command
  developer_tools/XSDSchemas/raven.xsd
  doc/user_guide/ravenRomTrainer.tex
  doc/user_manual/runInfo.tex
  framework/CustomModes/MPILegacySimulationMode.py
  framework/CustomModes/MPISimulationMode.py
  framework/Simulation.py
  scripts/establish_conda_env.sh
  tests/cluster_tests/test_mpiqsub_nosplit.xml
  tests/framework/user_guide/ravenTutorial/RomLoad.xml
Labels: FutureRAVENv2.1, Ready To Review

#1596 Upgrade to Tensorflow 2
  dependencies.xml
  framework/SupervisedLearning/KerasBase.py
  framework/SupervisedLearning/KerasClassifier.py
  framework/SupervisedLearning/KerasRegression.py
  tests/framework/ROM/tensorflow_keras/gold/LSTMRegression/out_resampled_0.csv
  tests/framework/ROM/tensorflow_keras/gold/LSTMRegression/out_resampled_1.csv
  tests/framework/ROM/tensorflow_keras/gold/data/outCon1DClassifier.csv
  tests/framework/ROM/tensorflow_keras/gold/data/outLSTMClassifier.csv
  tests/framework/ROM/tensorflow_keras/gold/diabetes/outMLPClassifier.csv
Labels: Ready To Review
