Repository idaholab/raven, pull requests merged in 2023-02, with the labels that each got.

#2057 Update matplotlib35
  dependencies.xml
  ravenframework/GridEntities.py
  ravenframework/Models/PostProcessors/LimitSurfaceIntegral.py
  ravenframework/OutStreams/PlotInterfaces/GeneralPlot.py
  ravenframework/Samplers/CustomSampler.py
  ravenframework/utils/plotUtils.py
  rook/Tester.py
Labels: Ready To Review

#2064 Windows Python 3.8, switch pip testing to 3.8 and 3.9 and update xarray and numpy
  dependencies.xml
  developer_tools/check_pip_packages.sh
  developer_tools/make_pip_packages.sh
  doc/workshop/forwardSampling/Inputs/tests
  ravenframework/Runners/SharedMemoryRunner.py
  ravenframework/SupervisedLearning/KerasBase.py
  tests/framework/unit_tests/utils/testDebugging.py
Labels: RAVENv2.3

#2073 Moving skip_if_OS from RavenFramework to Tester
  rook/Tester.py
  rook/doc/rook.tex
  scripts/TestHarness/testers/RavenFramework.py
  tests/reg_self_tests/only_not_windows.py
  tests/reg_self_tests/only_windows.py
  tests/reg_self_tests/tests
Labels: Ready To Review

#2079 Adding proposed fix for 2074
  ravenframework/PluginManager.py
Labels: Ready To Review

#2076 venv is part of python, so just use it instead of virtualenv
  scripts/establish_conda_env.sh
Labels: Ready To Review

#2086 Improve confusing warnings
  build_raven
  ravenframework/PluginManager.py
Labels: Ready To Review

#2084 Mandd/gawithcustomsampler
  ravenframework/CodeInterfaceClasses/MooseBasedApp/MooseInputParser.py
  ravenframework/Optimizers/Optimizer.py
  ravenframework/Samplers/CustomSampler.py
  tests/framework/Optimizers/GeneticAlgorithms/discrete/unconstrained/MaxwReplacement_customsampler/restart.csv
  tests/framework/Optimizers/GeneticAlgorithms/discrete/unconstrained/testGAMaxwRep_custom_sampler.xml
  tests/framework/Optimizers/GeneticAlgorithms/gold/discrete/unconstrained/MaxwReplacement_customsampler/opt_export_0.csv
  tests/framework/Optimizers/GeneticAlgorithms/tests
  tests/framework/ROM/TimeSeries/ARMA/tests
Labels: priority_normal, defect
