Repository idaholab/raven, pull requests merged in 2023-09, with the labels that each got.

#2172 XML Diff in Rook now can ignore nodes provided by user
  rook/XMLDiff.py
  tests/framework/TestDiffer/TestXMLDiffer.py
Labels: RAVENv3.0

#2010 Adding PARCS interface to replace SIMULATE3 interfafce
  doc/user_manual/code_interfaces/parcs.tex
  doc/user_manual/existing_interfaces.tex
  ravenframework/CodeInterfaceClasses/Factory.py
  ravenframework/CodeInterfaceClasses/PARCS/PARCSData.py
  ravenframework/CodeInterfaceClasses/PARCS/PARCSInterface.py
  ravenframework/CodeInterfaceClasses/PARCS/SpecificParser.py
  tests/framework/CodeInterfaceTests/PARCS/PARCS-RAVEN-GA/coremap.xml
  tests/framework/CodeInterfaceTests/PARCS/PARCS-RAVEN-GA/input.inp
  tests/framework/CodeInterfaceTests/PARCS/PARCS-RAVEN-GA/parcs-input-gen.xml
  tests/framework/CodeInterfaceTests/PARCS/PARCS-RAVEN-GA/sampleGA-PARCS/b1_r1/PATHS_message.out
  tests/framework/CodeInterfaceTests/PARCS/PARCS-RAVEN-GA/sampleGA-PARCS/b1_r1/input.inp.dep
  tests/framework/CodeInterfaceTests/PARCS/PARCS-RAVEN-GA/sampleGA-PARCS/b1_r1/input.inp.pin
  tests/framework/CodeInterfaceTests/PARCS/PARCS-RAVEN-GA/sampleGA-PARCS/b1_r2/PATHS_message.out
  tests/framework/CodeInterfaceTests/PARCS/PARCS-RAVEN-GA/sampleGA-PARCS/b1_r2/input.inp.dep
  tests/framework/CodeInterfaceTests/PARCS/PARCS-RAVEN-GA/sampleGA-PARCS/b1_r2/input.inp.pin
  tests/framework/CodeInterfaceTests/PARCS/PARCS-RAVEN-GA/sampleGA-PARCS/b2_r1/PATHS_message.out
  tests/framework/CodeInterfaceTests/PARCS/PARCS-RAVEN-GA/sampleGA-PARCS/b2_r1/input.inp.dep
  tests/framework/CodeInterfaceTests/PARCS/PARCS-RAVEN-GA/sampleGA-PARCS/b2_r1/input.inp.pin
  tests/framework/CodeInterfaceTests/PARCS/PARCS-RAVEN-GA/sampleGA-PARCS/b2_r2/PATHS_message.out
  tests/framework/CodeInterfaceTests/PARCS/PARCS-RAVEN-GA/sampleGA-PARCS/b2_r2/input.inp.dep
  tests/framework/CodeInterfaceTests/PARCS/PARCS-RAVEN-GA/sampleGA-PARCS/b2_r2/input.inp.pin
  tests/framework/CodeInterfaceTests/PARCS/PARCS-RAVEN-GA/sampleGA-PARCS/b3_r1/PATHS_message.out
  tests/framework/CodeInterfaceTests/PARCS/PARCS-RAVEN-GA/sampleGA-PARCS/b3_r1/input.inp.dep
  tests/framework/CodeInterfaceTests/PARCS/PARCS-RAVEN-GA/sampleGA-PARCS/b3_r1/input.inp.pin
  tests/framework/CodeInterfaceTests/PARCS/PARCS-RAVEN-GA/sampleGA-PARCS/b3_r2/PATHS_message.out
  tests/framework/CodeInterfaceTests/PARCS/PARCS-RAVEN-GA/sampleGA-PARCS/b3_r2/input.inp.dep
  tests/framework/CodeInterfaceTests/PARCS/PARCS-RAVEN-GA/sampleGA-PARCS/b3_r2/input.inp.pin
  tests/framework/CodeInterfaceTests/PARCS/constraints.py
  tests/framework/CodeInterfaceTests/PARCS/gold/PARCS-RAVEN-GA/optOut.csv
  tests/framework/CodeInterfaceTests/PARCS/gold/PARCS-RAVEN-GA/opt_export.csv
  tests/framework/CodeInterfaceTests/PARCS/gold/PARCS-RAVEN-GA/opt_export_0.csv
  tests/framework/CodeInterfaceTests/PARCS/test_GA-PARCS-LP.xml
  tests/framework/CodeInterfaceTests/PARCS/tests
Labels: Ready To Review, RAVENv3.0

#2184 ABCE using sqlite3
  .gitignore
  doc/user_manual/code_interfaces/abce.tex
  doc/user_manual/existing_interfaces.tex
  ravenframework/CodeInterfaceClasses/Abce/AbceCodeInterface.py
  ravenframework/CodeInterfaceClasses/Abce/__init__.py
  ravenframework/CodeInterfaceClasses/Factory.py
  tests/framework/CodeInterfaceTests/.gitignore
  tests/framework/CodeInterfaceTests/AbceInterfaceTest/inputs/C2N_project_definitions.yml
  tests/framework/CodeInterfaceTests/AbceInterfaceTest/inputs/demand_data.csv
  tests/framework/CodeInterfaceTests/AbceInterfaceTest/inputs/single_agent_testing.yml
  tests/framework/CodeInterfaceTests/AbceInterfaceTest/inputs/ts_data/timeseries_load_hourly.csv
  tests/framework/CodeInterfaceTests/AbceInterfaceTest/inputs/ts_data/timeseries_nspin_hourly.csv
  tests/framework/CodeInterfaceTests/AbceInterfaceTest/inputs/ts_data/timeseries_pv_hourly.csv
  tests/framework/CodeInterfaceTests/AbceInterfaceTest/inputs/ts_data/timeseries_reg_hourly.csv
  tests/framework/CodeInterfaceTests/AbceInterfaceTest/inputs/ts_data/timeseries_spin_hourly.csv
  tests/framework/CodeInterfaceTests/AbceInterfaceTest/inputs/ts_data/timeseries_wind_hourly.csv
  tests/framework/CodeInterfaceTests/AbceInterfaceTest/inputs/unit_specs.yml
  tests/framework/CodeInterfaceTests/AbceInterfaceTest/runAbceFake/1/outputs/ABCE_run/abce_db.db
  tests/framework/CodeInterfaceTests/AbceInterfaceTest/runAbceFake/2/outputs/ABCE_run/abce_db.db
  tests/framework/CodeInterfaceTests/AbceInterfaceTest/settings.yml
  tests/framework/CodeInterfaceTests/gold/AbceInterfaceTest/grid_0.csv
  tests/framework/CodeInterfaceTests/gold/AbceInterfaceTest/grid_1.csv
  tests/framework/CodeInterfaceTests/gold/AbceInterfaceTest/grid_fake.csv
  tests/framework/CodeInterfaceTests/gold/AbceInterfaceTest/runAbceFake/1/settings.yml
  tests/framework/CodeInterfaceTests/gold/abcesetting/samples.csv
  tests/framework/CodeInterfaceTests/gold/abcesetting/samples.xml
  tests/framework/CodeInterfaceTests/gold/abcesetting/sweep/1/settings.yml
  tests/framework/CodeInterfaceTests/test_Abce_code_interface.xml
  tests/framework/CodeInterfaceTests/test_Abce_code_interface_fake.xml
  tests/framework/CodeInterfaceTests/tests
Labels: Ready To Review, RAVENv3.0

#2138 Updating to tensorflow 2.13 and Macos arm issues
  dependencies.xml
  ravenframework/Optimizers/Factory.py
  ravenframework/Optimizers/__init__.py
  ravenframework/SupervisedLearning/KerasBase.py
  scripts/library_handler.py
  tests/framework/CodeInterfaceTests/CobraTF/tests
  tests/framework/Optimizers/BayesianOptimizer/tests
  tests/framework/PostProcessors/LimitSurface/tests
  tests/framework/Samplers/SparseGrid/tests
  tests/framework/pca_adaptive_sgc/gold/Adaptive/dump.xml
  tests/framework/pca_adaptive_sgc/tests
  tests/framework/pca_sparseGridCollocation/tests
  tests/framework/tests
Labels: Ready To Review
